// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label26;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label11;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label13;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label14;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LabelPM1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_LabelPM25;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_LabelPM10;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_LabelPM2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_LabelCO;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_LabelVOC;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_LabelNO2;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_LabelPM6;
extern lv_obj_t * ui_LabelSO2;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Label12;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_LabelPM7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_LabelOFF2;
extern bool switch_states;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_LabelOFF1;
extern lv_obj_t * ui_Dropdown1;
extern bool switch_states1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Label15;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_LabelPM3;
extern lv_obj_t * ui_LabelOFF4;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_LabelPM4;
extern lv_obj_t * ui_Dropdown2;
extern bool switch_states2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Label16;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_LabelPM5;
extern lv_obj_t * ui_Chart2;
extern lv_chart_series_t * ui_Chart2_series_1;
extern lv_chart_series_t * ui_Chart2_series_2;
extern lv_chart_series_t * ui_Chart2_series_3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_414099633);    // assets/images (1).png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
