// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 3);
    lv_obj_set_y(ui_Label5, -98);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "AQMS");

    ui_Label7 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -69);
    lv_obj_set_y(ui_Label7, -76);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "CO");

    ui_LabelCO = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelCO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCO, -71);
    lv_obj_set_y(ui_LabelCO, -43);
    lv_obj_set_align(ui_LabelCO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCO, "0");

    ui_Label8 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -68);
    lv_obj_set_y(ui_Label8, 1);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "VOC");

    ui_LabelVOC = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelVOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVOC, -69);
    lv_obj_set_y(ui_LabelVOC, 38);
    lv_obj_set_align(ui_LabelVOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVOC, "0");

    ui_Label9 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 75);
    lv_obj_set_y(ui_Label9, -79);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "NO2");

    ui_LabelNO2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelNO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNO2, 77);
    lv_obj_set_y(ui_LabelNO2, -43);
    lv_obj_set_align(ui_LabelNO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNO2, "0");

    ui_Button5 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button5, 64);
    lv_obj_set_height(ui_Button5, 30);
    lv_obj_set_x(ui_Button5, -116);
    lv_obj_set_y(ui_Button5, 93);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x29AAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Button5, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Button5, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPM6 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelPM6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPM6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPM6, -116);
    lv_obj_set_y(ui_LabelPM6, 93);
    lv_obj_set_align(ui_LabelPM6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPM6, "Back");

    ui_LabelSO2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelSO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSO2, 76);
    lv_obj_set_y(ui_LabelSO2, 36);
    lv_obj_set_align(ui_LabelSO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSO2, "0");

    ui_Label10 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 77);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SO2");

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}
