// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, -110);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "AQMS");

    ui_Button12 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button12, 64);
    lv_obj_set_height(ui_Button12, 30);
    lv_obj_set_x(ui_Button12, -111);
    lv_obj_set_y(ui_Button12, 85);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x29AAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Button12, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Button12, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPM3 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_LabelPM3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPM3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPM3, 0);
    lv_obj_set_y(ui_LabelPM3, -1);
    lv_obj_set_align(ui_LabelPM3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPM3, "Back");

    ui_LabelOFF4 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_LabelOFF4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOFF4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOFF4, -5);
    lv_obj_set_y(ui_LabelOFF4, -68);
    lv_obj_set_align(ui_LabelOFF4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOFF4, "Update System ?");

    ui_Button13 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button13, 64);
    lv_obj_set_height(ui_Button13, 30);
    lv_obj_set_x(ui_Button13, -6);
    lv_obj_set_y(ui_Button13, 29);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x29AAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0x4BFF69), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Button13, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Button13, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPM4 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_LabelPM4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPM4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPM4, 0);
    lv_obj_set_y(ui_LabelPM4, -1);
    lv_obj_set_align(ui_LabelPM4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPM4, "Yes");

    ui_Dropdown2 = lv_dropdown_create(ui_Screen6);
    lv_obj_set_width(ui_Dropdown2, 133);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, -4);
    lv_obj_set_y(ui_Dropdown2, -25);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);

}
