// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -98);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "AQMS");

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -107);
    lv_obj_set_y(ui_Label2, -31);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "PM1");

    ui_LabelPM1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelPM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPM1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPM1, -107);
    lv_obj_set_y(ui_LabelPM1, 1);
    lv_obj_set_align(ui_LabelPM1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPM1, "0");

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -2);
    lv_obj_set_y(ui_Label4, -32);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "PM25");

    ui_LabelPM25 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelPM25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPM25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPM25, -2);
    lv_obj_set_y(ui_LabelPM25, -1);
    lv_obj_set_align(ui_LabelPM25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPM25, "0");

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 102);
    lv_obj_set_y(ui_Label6, -33);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "PM10");

    ui_LabelPM10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelPM10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPM10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPM10, 102);
    lv_obj_set_y(ui_LabelPM10, -3);
    lv_obj_set_align(ui_LabelPM10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPM10, "0");

    ui_Button4 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 64);
    lv_obj_set_height(ui_Button4, 30);
    lv_obj_set_x(ui_Button4, -116);
    lv_obj_set_y(ui_Button4, 93);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x29AAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_Button4, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_Button4, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPM2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelPM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPM2, -116);
    lv_obj_set_y(ui_LabelPM2, 93);
    lv_obj_set_align(ui_LabelPM2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPM2, "Back");

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
